### ISSUE TITLE
WARNING: erroneous pipeline: no element "pipewiresrc"

### ISSUE THREAD

**Issue by prietus** [Rafostar/gst-rec#1]
I always get same errorWARNING: erroneous pipeline: no element "pipewiresrc"
I say error because the programs ends instead of starting to rec

LANG=C gst-rec --video width=1280,height=720,fps=25,scaling=true
Recording with auto-generated filename to: "/tmp"
Press Ctrl+c to stop
WARNING: erroneous pipeline: no element "pipewiresrc"
teraflops@hive ~  (propmt)

**Comment by Rafostar** [comment]
Screen recording on Wayland uses *pipewire*. I have not had time to properly test its implementation in my code. Until then please try recording on X11 desktop session.

**Comment by prietus** [comment]
I'm using xorg. arch linux. i3wm

**Comment by Rafostar** [comment]
Oh. That means the desktop session is incorrectly detected as Wayland. What is the value of your `XDG_SESSION_TYPE` env variable?
```
echo $XDG_SESSION_TYPE
```

Does starting app with:
```
XDG_SESSION_TYPE=x11 gst-rec
```
changes anything?

**Comment by prietus** [comment]
yeah, that was it. $XDG_SESSION_TYPE returns tty, 
setting it to x11 fixed the issue.
Thank you very much.

**Comment by x88** [comment]
`rm -rf ~/.cache/gstreamer-1.0`
Works for me
