### ISSUE TITLE
Cast desktop to stdout not working

### ISSUE THREAD

**Issue by myisaak** [Rafostar/gst-rec#3]
I attempted the following command described on the README (with the added DEBUG=castnow* for debugging) :
```bash
gst-rec --video width=1920,height=1080,scaling=true -o - | DEBUG=castnow* castnow --silent -
```

to get a result from castnow saying the **piped stdin is undefined**:
```bash
castnow volume step: 0.05 +0ms
castnow attaching... +1ms
**castnow:stdin undefined +0ms**
castnow player status: scanning +1ms
castnow player status: connecting +340ms
castnow player status: finding +386ms
castnow player status: joining +103ms
castnow player status: ready +2ms
```

I noticed the following error form the pipewire service:
```
Apr 16 16:28:41 stromae pipewire[43293]: [W][000018933.848217][module-protocol-native.c:370 client_new()] server 0xcb997e39b0: no pe>
Apr 16 16:28:42 stromae pipewire[43293]: [E][000018933.963878][v4l2-source.c:601 port_set_format()] can't parse video raw
Apr 16 16:28:42 stromae pipewire[43293]: [E][000018933.963913][impl-link.c:118 pw_impl_link_update_state()] link 0xcb99923a00: updat>
```

I think this has to be an issue from gst-rec, gstreamer or pipewire.

I'm on Arch Linux with kernel 5.6.3.a-1-hardened.

Packages explicitly installed:
- gstreamer 1.16.2-1
- pipewire 0.3.2-1
- gst-plugins-base 1.16.2-1
- gst-plugins-good 1.16.2-3
- gst-plugins-bad 1.16.2-7
- gst-plugins-ugly 1.16.2-3
- x264 3:0.159.r2999.296494a-1

**Comment by Rafostar** [comment]
Is this on Wayland or Xorg?

**Comment by myisaak** [comment]
It’s on Wayland.

**Comment by Rafostar** [comment]
It might be a Wayland problem here. The app uses GStreamer defaults when creating pipewire video pipe on Wayland. Can you check on Xorg session? Starting with:
```
XDG_SESSION_TYPE=x11 gst-rec
```
Might solve it on Xorg if it still occurs.

Also, I know that it is not an answer here, but if you happen to be on Arch with GNOME, then I made a better implementation of desktop streaming to Chromecast in my recent [Cast to TV v14](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv) extension that should work on Wayland without problems (and have better performance than combination of `gst-rec` + `castnow`).

**Comment by myisaak** [comment]
Changing the session type allowed the stream to pass into stdin but only the mouse was visible behind a black screen.

I fixed the issue by installing a display manager gddm instead of manually starting from tty. The video now streams!
