### ISSUE TITLE
Can this be used to stream to an RTMP Server?

### ISSUE THREAD

**Issue by deftdawg** [Rafostar/gst-rec#6]
I'm able to record locally, that is pretty cool and I noticed some server options in the example, but I'm curious to know if there's a way to have this stream to an RTMP server?

Thanks for reading.

**Comment by Rafostar** [comment]
This was meant as a simple record tool integrating GStreamer with node.js. For doing what you want, using a manual single GStreamer pipeline would be more efficient.

**Comment by deftdawg** [comment]
Ok, thanks you for responding. 🍻
